export const AuthApi = {
  signupStart: '/auth/signup/start',
  signupResendOtp: '/auth/signup/resend-otp',
  signupVerifyOtp: '/auth/signup/verify-otp',
  signupCompleteProfile: '/auth/signup/complete-profile',
  signin: '/auth/signin',
  signout: '/auth/signout',
  signoutAll: '/auth/signout-all',
  refresh: '/auth/refresh',
  me: '/auth/me',
  sessions: '/auth/sessions',
  registrationStatus: '/auth/registration/status',
  passwordForgot: '/auth/password/forgot',
  passwordReset: '/auth/password/reset',
  setPassword: '/auth/set-password',
  google: '/auth/google',
  googleLinkIntent: '/auth/google/link-intent',
  googleHandoffExchange: '/auth/google/handoff/exchange',
} as const
